import { vars } from "nativewind";

export const themes = {
  light: vars({
    "--color-background": "#FFFFFF",
    "--color-backgroundSecondary": "#F4FBFB",
    "--color-backgroundMuted": "#F1F5F9",
    "--color-foreground": "#1E293B",
    "--color-foregroundSecondary": "#515d71",
    "--color-foregroundMuted": "#64748B",
    "--color-card": "#F4FBFB",
    "--color-cardForeground": "#1E293B",
    "--color-border": "#E2E8F0",
    "--color-input": "#F1F5F9",
    "--color-ring": "#3B82F6",
    "--color-secondary": "#D4D4D4",
    "--color-primaryForeground": "#FFFFFF",
    "--color-primary": "#4820c1",
    "--color-secondaryForeground": "#FFFFFF",
    "--color-success": "#10B981",
    "--color-warning": "#db7d0f",
    "--color-error": "#cc4b37",
    "--color-info": "#3B82F6",
    "--color-text": "#FFFFFFF",
  }),
  dark: vars({
    "--color-background": "#0F172A",
    "--color-backgroundSecondary": "#1E293B",
    "--color-backgroundMuted": "#334155",
    "--color-foreground": "#F1F5F9",
    "--color-foregroundSecondary": "#E2E8F0",
    "--color-foregroundMuted": "#94A3B8",
    "--color-card": "#1E293B",
    "--color-cardForeground": "#F1F5F9",
    "--color-border": "#334155",
    "--color-input": "#334155",
    "--color-ring": "#60A5FA",
    "--color-primary": "#55267e",
    "--color-primaryForeground": "#1E293B",
    "--color-secondary": "#334155",
    "--color-secondaryForeground": "#F1F5F9",
    "--color-success": "#3e9777",
    "--color-warning": "#8f551e",
    "--color-error": "#e61616",
    "--color-info": "#204e85",
    "--color-text": "#D4D4D4",
  }),
};
